### ISSUE TITLE
Terminals & Shells

### ISSUE THREAD

**Issue by Mafrans** [wiktoriavh/learn-web-dev-svelte#1]
_Continuation of https://github.com/Braweria/learn-web-dev/issues/14_

I think it's important that we introduce the concept of a terminal and a shell in succession, and make sure to separate them out into individual concepts. It's easy for a beginner to get them mixed up (in fact, many guides regularly do).

Almost every linux distro uses bash as its default shell, [MacOS uses zsh as of Catalina (2019)](https://www.theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features) and, ever since Windows Terminal released, Windows's default shell has been PowerShell. Personally I use zsh, but either bash or zsh should be a good introductory option. Windows does not support either without WSL, which poses a problem - if we can't accept PS we will have to introduce WSL *before* the concept of a shell, even though WSL itself is presented through a shell.

As for terminals, MacOS and Windows both come pre-installed with decent terminals that could be introduced, but on Linux it really depends on which desktop environment you have installed (GNOME uses Gnome Terminal, KDE uses Konsole, Sway uses Foot, etc.). One option could be to simply ditch the default terminal and recommend a cross-platform terminal like [Kitty](https://sw.kovidgoyal.net/kitty/).

**Comment by wiktoriavh** [comment]
https://github.com/Braweria/learn-web-dev/issues/14
