### ISSUE TITLE
Card design and structure

### ISSUE THREAD

**Issue by Mafrans** [wiktoriavh/learn-web-dev-svelte#2]
_Continuation of https://github.com/Braweria/learn-web-dev/issues/52_

With the new website, it's worth putting more thought into how we want to introduce topics, and whether cards like [these](https://github.com/Braweria/learn-web-dev-svelte/assets/11413481/aa283014-2e55-46fd-88e5-f2d010cd6889) are necessary the best way to do so. 

I put up [a design](https://play.tailwindcss.com/zgyJsq7Lr1) as an option for how a card based system could work, but that does not necessarily mean I think it's the best way to go ahead. I will leave this issue open as I explore other possibilities.

**Comment by wiktoriavh** [comment]
Discussion will be continued in the old issue on the project board: https://github.com/users/Braweria/projects/3/views/1?pane=issue&itemId=14203118
